### ISSUE TITLE
No option for `downgrade_pkg` argument

### ISSUE THREAD

**Issue by matclab** [JustinTimperio/pacback#27]
**Describe the Bug:**\

Python exception

**Output of Command**
- Output sent to the user in terminal
```
$ sudo pacback -c 1          
Building Light Restore Point 01...
Restore Point Creation Complete!
Traceback (most recent call last):
  File "/usr/bin/pacback", line 124, in <module>
    if args.downgrade_pkg:
AttributeError: 'Namespace' object has no attribute 'downgrade_pkg'
```
- Log output in /var/log/pacback.log
```
[17:01:30.132627] session.lock(): Started Logging Session
[17:01:30.132665] session.lock(): Passed Root Check
[17:01:30.135966] session.lock(): Started Active Session
[17:01:30.136105] session.setup(): User Config File Is Missing!
[17:01:30.136338] create.restore_point(01): Started Restore Point Creation...
[17:01:30.136398] create.restore_point(01): All Checks Passed! Handing Off to create.main()
[17:01:30.136450] create.main(rp01): Building ID:01 As Light Restore Point
[17:01:30.158638] create.main(rp01): Generated Meta Data File
[17:01:30.159192] create.main(rp01): Generated Meta Data Checksum
[17:01:30.159229] create.main(rp01): Main Build Complete of ID:01 As Light Restore Point
[17:01:30.159362] create.restore_point(01): Restore Point Creation Complete!
```
- Config file in /etc/pacback/config
```
$LC_ALL=C cat /etc/pacback/config
cat: /etc/pacback/config: No such file or directory
```

**Machine (please fill in the following information):**
 - Kernel Version: (`uname -r `) : `5.8.7-arch1-1`
 - Python Version: (`python3 --version`) : `Python 3.8.5`
 - Python Rich Version (`pacman -Q | grep python-rich`): `python-rich 6.0.0-1`
 - Python Requests Version (`pacman -Q | grep python-requests`): `python-requests 2.24.0-1`
 - Pacback Version: (`sudo pacback -v`)
```
sudo pacback -v                 
Pacback Version: 2.0.0
PAF Version: 256fc62
Traceback (most recent call last):
  File "/usr/bin/pacback", line 88, in <module>
    cache = utils.cache_size(config)
  File "/usr/share/pacback/core/utils.py", line 310, in cache_size
    all_paths = find_pkgs_in_dir(fs_paths)
  File "/usr/share/pacback/core/utils.py", line 35, in find_pkgs_in_dir
    cache = {f for f in paf.find_files(path)
  File "/usr/share/pacback/core/paf/file.py", line 72, in find_files
    z = scan_dir(x)
  File "/usr/share/pacback/core/paf/file.py", line 19, in scan_dir
    for x in os.scandir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lost+found/.cache'
```
 - Install Type: (pacback vs pacback-git): `pacback-git` modified with the following `prepare` section:
```
prepare() {
  cd "${srcdir}/pacback"
  git submodule update --init --recursive
}
```

**Comment by JustinTimperio** [comment]
Hey @matclab, currently I am working on updating the build package with @Grq3  but they currently aren't done. It's been a little slow going because we are in different time zones. I'm hoping that we will be able to finish it by the end of the day but it may not happen. 

You are getting this error because I have basically re-written 80% of pacback so the whole build process needs to be overhauled. I'll let you know when this fixed our you can follow our conversation on gitter.

Thanks!

**Comment by JustinTimperio** [comment]
We have finally arrived got the build packages working so you can install the most recent git version using the AUR package. In the future, I do not recommend manually installing pacback using the files in /build. Those scripts are used for maintainers and developers when bug testing and staging new releases.

https://aur.archlinux.org/packages/pacback-git
