### ISSUE TITLE
Popen Error in `utils.reboot_check()`

### ISSUE THREAD

**Issue by JustinTimperio** [JustinTimperio/pacback#32]
**Describe the Bug:**\
Failure during downgrade.

**Output of Command**
```
Traceback (most recent call last):
  File "/usr/bin/pacback", line 134, in <module>
    restore.restore_point(config, args.restore_point)
  File "/usr/share/pacback/core/restore.py", line 182, in restore_point
    utils.reboot_check(config)
  File "/usr/share/pacback/core/utils.py", line 298, in reboot_check
    if raw[0].strip() != raw[1].strip():
TypeError: 'Popen' object is not subscriptable
```

**Machine (please fill in the following information):**
 - Install Type: (both)

**Comment by JustinTimperio** [comment]
Effects:
Version - 2.0.1
Version - 2.0.2
Version - 2.0.3

**Comment by JustinTimperio** [comment]
Patched by:
pacback-git >= r116.acbb480
pacback >= 2.0.3-1
